### ISSUE TITLE
Nft history nested under nft

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/api#2]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to see the history for an nft. I'd also like to be able to extract the begging and ending timestamp from the `timestamp_range` property

```graphql
query OneNftAndHistory {
  nft(limit: 1) {
    history {
      timestamp_range
      start_timestamp
      end_timestamp
    }
  }
}
```

**Comment by hgraphql** [comment]
closing as complete

**Comment by hgraphql** [comment]
@itsbrandondev I'm going to integrate new feature development for the API in this repo and replicate the project management structure we're using in WalletConnect

**Comment by itsbrandondev** [comment]
sounds good 🫡
